name: Build

on: workflow_dispatch 

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          # install: git mingw-w64-x86_64-toolchain

    - name: Build x86
      shell: cmd
      run: call build.bat x86
    
    - name: Build x64
      shell: cmd
      run: call build.bat

    - uses: actions/upload-artifact@v2
      with:
        name: gnumake
        path: |
          ./dist
        if-no-files-found: ignore # 'warn' or 'ignore' are also available, defaults to `warn`
        retention-days: 1
