name: Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag of make'
        required: true

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
        - 'x86'
        - 'x64'

    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        # install: git mingw-w64-x86_64-toolchain

    - name: Build
      shell: cmd
      run: call build.bat --arch ${{ matrix.arch }} --tag ${{ github.event.inputs.tag }}

    - uses: actions/upload-artifact@v4
      with:
        name: gnumake-msvc-${{ matrix.arch }}
        path: |
          ./dist
        if-no-files-found: ignore # 'warn' or 'ignore' are also available, defaults to `warn`
        retention-days: 1
